/*
 * Generated by Bluespec Compiler, version 2016.03.beta1 (build 34761, 2016-03-16)
 * 
 * On Thu Sep 29 17:14:31 IST 2016
 * 
 */
#include "bluesim_primitives.h"
#include "mkBBD.h"


/* Constructor */
MOD_mkBBD::MOD_mkBBD(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_counter(simHdl, "counter", this, 32u, 0u, (tUInt8)0u),
    INST_dataval(simHdl, "dataval", this, 32u, 0u, (tUInt8)0u),
    INST_fifo_in(simHdl, "fifo_in", this, 32u, 64u, 1u, 0u),
    INST_matrix_vec_0(simHdl, "matrix_vec_0", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_1(simHdl, "matrix_vec_1", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_10(simHdl, "matrix_vec_10", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_11(simHdl, "matrix_vec_11", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_12(simHdl, "matrix_vec_12", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_13(simHdl, "matrix_vec_13", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_14(simHdl, "matrix_vec_14", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_15(simHdl, "matrix_vec_15", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_2(simHdl, "matrix_vec_2", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_3(simHdl, "matrix_vec_3", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_4(simHdl, "matrix_vec_4", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_5(simHdl, "matrix_vec_5", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_6(simHdl, "matrix_vec_6", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_7(simHdl, "matrix_vec_7", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_8(simHdl, "matrix_vec_8", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_matrix_vec_9(simHdl, "matrix_vec_9", this, 8u, (tUInt8)0u, (tUInt8)0u),
    INST_row_select(simHdl, "row_select", this, 32u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  PORT_EN_push_data = false;
  PORT_push_data_d1 = 0u;
  PORT_RDY_push_data = false;
  symbol_count = 28u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkBBD::init_symbols_0()
{
  init_symbol(&symbols[0u], "CAN_FIRE_push_data", SYM_DEF, &DEF_CAN_FIRE_push_data, 1u);
  init_symbol(&symbols[1u], "CAN_FIRE_RL_matrix_in", SYM_DEF, &DEF_CAN_FIRE_RL_matrix_in, 1u);
  init_symbol(&symbols[2u], "counter", SYM_MODULE, &INST_counter);
  init_symbol(&symbols[3u], "dataval", SYM_MODULE, &INST_dataval);
  init_symbol(&symbols[4u], "EN_push_data", SYM_PORT, &PORT_EN_push_data, 1u);
  init_symbol(&symbols[5u], "fifo_in", SYM_MODULE, &INST_fifo_in);
  init_symbol(&symbols[6u], "matrix_vec_0", SYM_MODULE, &INST_matrix_vec_0);
  init_symbol(&symbols[7u], "matrix_vec_1", SYM_MODULE, &INST_matrix_vec_1);
  init_symbol(&symbols[8u], "matrix_vec_10", SYM_MODULE, &INST_matrix_vec_10);
  init_symbol(&symbols[9u], "matrix_vec_11", SYM_MODULE, &INST_matrix_vec_11);
  init_symbol(&symbols[10u], "matrix_vec_12", SYM_MODULE, &INST_matrix_vec_12);
  init_symbol(&symbols[11u], "matrix_vec_13", SYM_MODULE, &INST_matrix_vec_13);
  init_symbol(&symbols[12u], "matrix_vec_14", SYM_MODULE, &INST_matrix_vec_14);
  init_symbol(&symbols[13u], "matrix_vec_15", SYM_MODULE, &INST_matrix_vec_15);
  init_symbol(&symbols[14u], "matrix_vec_2", SYM_MODULE, &INST_matrix_vec_2);
  init_symbol(&symbols[15u], "matrix_vec_3", SYM_MODULE, &INST_matrix_vec_3);
  init_symbol(&symbols[16u], "matrix_vec_4", SYM_MODULE, &INST_matrix_vec_4);
  init_symbol(&symbols[17u], "matrix_vec_5", SYM_MODULE, &INST_matrix_vec_5);
  init_symbol(&symbols[18u], "matrix_vec_6", SYM_MODULE, &INST_matrix_vec_6);
  init_symbol(&symbols[19u], "matrix_vec_7", SYM_MODULE, &INST_matrix_vec_7);
  init_symbol(&symbols[20u], "matrix_vec_8", SYM_MODULE, &INST_matrix_vec_8);
  init_symbol(&symbols[21u], "matrix_vec_9", SYM_MODULE, &INST_matrix_vec_9);
  init_symbol(&symbols[22u], "push_data_d1", SYM_PORT, &PORT_push_data_d1, 32u);
  init_symbol(&symbols[23u], "RDY_push_data", SYM_PORT, &PORT_RDY_push_data, 1u);
  init_symbol(&symbols[24u], "RL_matrix_in", SYM_RULE);
  init_symbol(&symbols[25u], "row_select", SYM_MODULE, &INST_row_select);
  init_symbol(&symbols[26u], "WILL_FIRE_push_data", SYM_DEF, &DEF_WILL_FIRE_push_data, 1u);
  init_symbol(&symbols[27u], "WILL_FIRE_RL_matrix_in", SYM_DEF, &DEF_WILL_FIRE_RL_matrix_in, 1u);
}


/* Rule actions */

void MOD_mkBBD::RL_matrix_in()
{
  tUInt32 DEF_x__h1256;
  tUInt32 DEF_x__h1296;
  tUInt32 DEF_x__h2319;
  tUInt32 DEF_x__h2856;
  tUInt32 DEF_x__h3393;
  tUInt32 DEF_counter_BITS_29_TO_0___h3400;
  tUInt32 DEF_x__h1281;
  tUInt32 DEF_fifo_in_first____d9;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_15___d61;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_14___d60;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_13___d59;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_12___d58;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_11___d57;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_10___d56;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_9___d55;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_8___d54;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_7___d53;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_6___d52;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_5___d51;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_4___d50;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_3___d49;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_2___d48;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_1___d47;
  tUInt8 DEF_x__h3449;
  tUInt8 DEF_x__h2912;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_0___d45;
  tUInt8 DEF__dfoo1;
  tUInt8 DEF__dfoo2;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_15___d43;
  tUInt8 DEF__dfoo3;
  tUInt8 DEF__dfoo4;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_14___d42;
  tUInt8 DEF__dfoo5;
  tUInt8 DEF__dfoo6;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_13___d41;
  tUInt8 DEF__dfoo7;
  tUInt8 DEF__dfoo8;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_12___d40;
  tUInt8 DEF__dfoo9;
  tUInt8 DEF__dfoo10;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_11___d39;
  tUInt8 DEF__dfoo11;
  tUInt8 DEF__dfoo12;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_10___d38;
  tUInt8 DEF__dfoo13;
  tUInt8 DEF__dfoo14;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_9___d37;
  tUInt8 DEF__dfoo15;
  tUInt8 DEF__dfoo16;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_8___d36;
  tUInt8 DEF__dfoo17;
  tUInt8 DEF__dfoo18;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_7___d35;
  tUInt8 DEF__dfoo19;
  tUInt8 DEF__dfoo20;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_6___d34;
  tUInt8 DEF__dfoo21;
  tUInt8 DEF__dfoo22;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_5___d33;
  tUInt8 DEF__dfoo23;
  tUInt8 DEF__dfoo24;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_4___d32;
  tUInt8 DEF__dfoo25;
  tUInt8 DEF__dfoo26;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_3___d31;
  tUInt8 DEF__dfoo27;
  tUInt8 DEF__dfoo28;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_2___d30;
  tUInt8 DEF__dfoo29;
  tUInt8 DEF__dfoo30;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_1___d29;
  tUInt8 DEF__dfoo31;
  tUInt8 DEF__dfoo32;
  tUInt8 DEF_x__h2375;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_0___d27;
  tUInt8 DEF__dfoo33;
  tUInt8 DEF__dfoo34;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_15___d25;
  tUInt8 DEF__dfoo66;
  tUInt8 DEF__dfoo35;
  tUInt8 DEF__dfoo36;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_14___d24;
  tUInt8 DEF__dfoo68;
  tUInt8 DEF__dfoo37;
  tUInt8 DEF__dfoo38;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_13___d23;
  tUInt8 DEF__dfoo70;
  tUInt8 DEF__dfoo39;
  tUInt8 DEF__dfoo40;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_12___d22;
  tUInt8 DEF__dfoo72;
  tUInt8 DEF__dfoo41;
  tUInt8 DEF__dfoo42;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_11___d21;
  tUInt8 DEF__dfoo74;
  tUInt8 DEF__dfoo43;
  tUInt8 DEF__dfoo44;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_10___d20;
  tUInt8 DEF__dfoo76;
  tUInt8 DEF__dfoo45;
  tUInt8 DEF__dfoo46;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_9___d19;
  tUInt8 DEF__dfoo78;
  tUInt8 DEF__dfoo47;
  tUInt8 DEF__dfoo48;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_8___d18;
  tUInt8 DEF__dfoo80;
  tUInt8 DEF__dfoo49;
  tUInt8 DEF__dfoo50;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_7___d17;
  tUInt8 DEF__dfoo82;
  tUInt8 DEF__dfoo51;
  tUInt8 DEF__dfoo52;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_6___d16;
  tUInt8 DEF__dfoo84;
  tUInt8 DEF__dfoo53;
  tUInt8 DEF__dfoo54;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_5___d15;
  tUInt8 DEF__dfoo86;
  tUInt8 DEF__dfoo55;
  tUInt8 DEF__dfoo56;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_4___d14;
  tUInt8 DEF__dfoo88;
  tUInt8 DEF__dfoo57;
  tUInt8 DEF__dfoo58;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_3___d13;
  tUInt8 DEF__dfoo90;
  tUInt8 DEF__dfoo59;
  tUInt8 DEF__dfoo60;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_2___d12;
  tUInt8 DEF__dfoo92;
  tUInt8 DEF__dfoo61;
  tUInt8 DEF__dfoo62;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_1___d11;
  tUInt8 DEF__dfoo94;
  tUInt8 DEF__dfoo63;
  tUInt8 DEF__dfoo64;
  tUInt8 DEF_x__h1835;
  tUInt8 DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_0___d8;
  tUInt8 DEF__dfoo96;
  tUInt8 DEF__dfoo95;
  tUInt8 DEF__dfoo93;
  tUInt8 DEF__dfoo91;
  tUInt8 DEF__dfoo89;
  tUInt8 DEF__dfoo87;
  tUInt8 DEF__dfoo85;
  tUInt8 DEF__dfoo83;
  tUInt8 DEF__dfoo81;
  tUInt8 DEF__dfoo79;
  tUInt8 DEF__dfoo77;
  tUInt8 DEF__dfoo75;
  tUInt8 DEF__dfoo73;
  tUInt8 DEF__dfoo71;
  tUInt8 DEF__dfoo69;
  tUInt8 DEF__dfoo67;
  tUInt8 DEF__dfoo65;
  DEF_fifo_in_first____d9 = INST_fifo_in.METH_first();
  DEF_x__h1835 = (tUInt8)((tUInt8)255u & DEF_fifo_in_first____d9);
  DEF_x__h2375 = (tUInt8)((tUInt8)255u & (DEF_fifo_in_first____d9 >> 8u));
  DEF_x__h2912 = (tUInt8)((tUInt8)255u & (DEF_fifo_in_first____d9 >> 16u));
  DEF_x__h3449 = (tUInt8)(DEF_fifo_in_first____d9 >> 24u);
  DEF_x__h1281 = INST_counter.METH_read();
  DEF_counter_BITS_29_TO_0___h3400 = (tUInt32)(1073741823u & DEF_x__h1281);
  DEF_x__h3393 = (DEF_counter_BITS_29_TO_0___h3400 << 2u) | (tUInt32)((tUInt8)3u);
  DEF_x__h2856 = (DEF_counter_BITS_29_TO_0___h3400 << 2u) | (tUInt32)((tUInt8)2u);
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_0___d45 = DEF_x__h2856 == 0u;
  DEF__dfoo32 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_0___d45 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo31 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_0___d45 || DEF_x__h3393 == 0u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_1___d47 = DEF_x__h2856 == 1u;
  DEF__dfoo30 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_1___d47 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo29 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_1___d47 || DEF_x__h3393 == 1u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_2___d48 = DEF_x__h2856 == 2u;
  DEF__dfoo28 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_2___d48 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo27 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_2___d48 || DEF_x__h3393 == 2u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_3___d49 = DEF_x__h2856 == 3u;
  DEF__dfoo26 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_3___d49 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo25 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_3___d49 || DEF_x__h3393 == 3u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_4___d50 = DEF_x__h2856 == 4u;
  DEF__dfoo24 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_4___d50 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo23 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_4___d50 || DEF_x__h3393 == 4u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_5___d51 = DEF_x__h2856 == 5u;
  DEF__dfoo22 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_5___d51 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo21 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_5___d51 || DEF_x__h3393 == 5u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_6___d52 = DEF_x__h2856 == 6u;
  DEF__dfoo20 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_6___d52 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo19 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_6___d52 || DEF_x__h3393 == 6u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_7___d53 = DEF_x__h2856 == 7u;
  DEF__dfoo18 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_7___d53 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo17 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_7___d53 || DEF_x__h3393 == 7u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_8___d54 = DEF_x__h2856 == 8u;
  DEF__dfoo16 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_8___d54 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo15 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_8___d54 || DEF_x__h3393 == 8u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_9___d55 = DEF_x__h2856 == 9u;
  DEF__dfoo14 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_9___d55 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo13 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_9___d55 || DEF_x__h3393 == 9u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_10___d56 = DEF_x__h2856 == 10u;
  DEF__dfoo12 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_10___d56 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo11 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_10___d56 || DEF_x__h3393 == 10u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_11___d57 = DEF_x__h2856 == 11u;
  DEF__dfoo10 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_11___d57 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo9 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_11___d57 || DEF_x__h3393 == 11u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_12___d58 = DEF_x__h2856 == 12u;
  DEF__dfoo8 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_12___d58 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo7 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_12___d58 || DEF_x__h3393 == 12u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_13___d59 = DEF_x__h2856 == 13u;
  DEF__dfoo6 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_13___d59 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo5 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_13___d59 || DEF_x__h3393 == 13u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_15___d61 = DEF_x__h2856 == 15u;
  DEF__dfoo2 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_15___d61 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo1 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_15___d61 || DEF_x__h3393 == 15u;
  DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_14___d60 = DEF_x__h2856 == 14u;
  DEF__dfoo4 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_14___d60 ? DEF_x__h2912 : DEF_x__h3449;
  DEF__dfoo3 = DEF_counter_BITS_29_TO_0_CONCAT_2_4_EQ_14___d60 || DEF_x__h3393 == 14u;
  DEF_x__h2319 = (DEF_counter_BITS_29_TO_0___h3400 << 2u) | (tUInt32)((tUInt8)1u);
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_0___d27 = DEF_x__h2319 == 0u;
  DEF__dfoo64 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_0___d27 ? DEF_x__h2375 : DEF__dfoo32;
  DEF__dfoo63 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_0___d27 || DEF__dfoo31;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_1___d29 = DEF_x__h2319 == 1u;
  DEF__dfoo62 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_1___d29 ? DEF_x__h2375 : DEF__dfoo30;
  DEF__dfoo61 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_1___d29 || DEF__dfoo29;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_2___d30 = DEF_x__h2319 == 2u;
  DEF__dfoo60 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_2___d30 ? DEF_x__h2375 : DEF__dfoo28;
  DEF__dfoo59 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_2___d30 || DEF__dfoo27;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_3___d31 = DEF_x__h2319 == 3u;
  DEF__dfoo58 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_3___d31 ? DEF_x__h2375 : DEF__dfoo26;
  DEF__dfoo57 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_3___d31 || DEF__dfoo25;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_4___d32 = DEF_x__h2319 == 4u;
  DEF__dfoo56 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_4___d32 ? DEF_x__h2375 : DEF__dfoo24;
  DEF__dfoo55 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_4___d32 || DEF__dfoo23;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_5___d33 = DEF_x__h2319 == 5u;
  DEF__dfoo54 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_5___d33 ? DEF_x__h2375 : DEF__dfoo22;
  DEF__dfoo53 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_5___d33 || DEF__dfoo21;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_6___d34 = DEF_x__h2319 == 6u;
  DEF__dfoo52 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_6___d34 ? DEF_x__h2375 : DEF__dfoo20;
  DEF__dfoo51 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_6___d34 || DEF__dfoo19;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_7___d35 = DEF_x__h2319 == 7u;
  DEF__dfoo50 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_7___d35 ? DEF_x__h2375 : DEF__dfoo18;
  DEF__dfoo49 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_7___d35 || DEF__dfoo17;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_8___d36 = DEF_x__h2319 == 8u;
  DEF__dfoo48 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_8___d36 ? DEF_x__h2375 : DEF__dfoo16;
  DEF__dfoo47 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_8___d36 || DEF__dfoo15;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_9___d37 = DEF_x__h2319 == 9u;
  DEF__dfoo46 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_9___d37 ? DEF_x__h2375 : DEF__dfoo14;
  DEF__dfoo45 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_9___d37 || DEF__dfoo13;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_10___d38 = DEF_x__h2319 == 10u;
  DEF__dfoo44 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_10___d38 ? DEF_x__h2375 : DEF__dfoo12;
  DEF__dfoo43 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_10___d38 || DEF__dfoo11;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_11___d39 = DEF_x__h2319 == 11u;
  DEF__dfoo42 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_11___d39 ? DEF_x__h2375 : DEF__dfoo10;
  DEF__dfoo41 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_11___d39 || DEF__dfoo9;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_12___d40 = DEF_x__h2319 == 12u;
  DEF__dfoo40 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_12___d40 ? DEF_x__h2375 : DEF__dfoo8;
  DEF__dfoo39 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_12___d40 || DEF__dfoo7;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_13___d41 = DEF_x__h2319 == 13u;
  DEF__dfoo38 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_13___d41 ? DEF_x__h2375 : DEF__dfoo6;
  DEF__dfoo37 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_13___d41 || DEF__dfoo5;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_14___d42 = DEF_x__h2319 == 14u;
  DEF__dfoo36 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_14___d42 ? DEF_x__h2375 : DEF__dfoo4;
  DEF__dfoo35 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_14___d42 || DEF__dfoo3;
  DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_15___d43 = DEF_x__h2319 == 15u;
  DEF__dfoo34 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_15___d43 ? DEF_x__h2375 : DEF__dfoo2;
  DEF__dfoo33 = DEF_counter_BITS_29_TO_0_CONCAT_1_6_EQ_15___d43 || DEF__dfoo1;
  DEF_x__h1296 = (DEF_counter_BITS_29_TO_0___h3400 << 2u) | (tUInt32)((tUInt8)0u);
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_0___d8 = DEF_x__h1296 == 0u;
  DEF__dfoo95 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_0___d8 || DEF__dfoo63;
  DEF__dfoo96 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_0___d8 ? DEF_x__h1835 : DEF__dfoo64;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_1___d11 = DEF_x__h1296 == 1u;
  DEF__dfoo93 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_1___d11 || DEF__dfoo61;
  DEF__dfoo94 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_1___d11 ? DEF_x__h1835 : DEF__dfoo62;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_2___d12 = DEF_x__h1296 == 2u;
  DEF__dfoo91 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_2___d12 || DEF__dfoo59;
  DEF__dfoo92 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_2___d12 ? DEF_x__h1835 : DEF__dfoo60;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_3___d13 = DEF_x__h1296 == 3u;
  DEF__dfoo89 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_3___d13 || DEF__dfoo57;
  DEF__dfoo90 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_3___d13 ? DEF_x__h1835 : DEF__dfoo58;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_4___d14 = DEF_x__h1296 == 4u;
  DEF__dfoo87 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_4___d14 || DEF__dfoo55;
  DEF__dfoo88 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_4___d14 ? DEF_x__h1835 : DEF__dfoo56;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_5___d15 = DEF_x__h1296 == 5u;
  DEF__dfoo85 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_5___d15 || DEF__dfoo53;
  DEF__dfoo86 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_5___d15 ? DEF_x__h1835 : DEF__dfoo54;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_6___d16 = DEF_x__h1296 == 6u;
  DEF__dfoo83 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_6___d16 || DEF__dfoo51;
  DEF__dfoo84 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_6___d16 ? DEF_x__h1835 : DEF__dfoo52;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_7___d17 = DEF_x__h1296 == 7u;
  DEF__dfoo81 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_7___d17 || DEF__dfoo49;
  DEF__dfoo82 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_7___d17 ? DEF_x__h1835 : DEF__dfoo50;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_8___d18 = DEF_x__h1296 == 8u;
  DEF__dfoo79 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_8___d18 || DEF__dfoo47;
  DEF__dfoo80 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_8___d18 ? DEF_x__h1835 : DEF__dfoo48;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_9___d19 = DEF_x__h1296 == 9u;
  DEF__dfoo77 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_9___d19 || DEF__dfoo45;
  DEF__dfoo78 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_9___d19 ? DEF_x__h1835 : DEF__dfoo46;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_10___d20 = DEF_x__h1296 == 10u;
  DEF__dfoo75 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_10___d20 || DEF__dfoo43;
  DEF__dfoo76 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_10___d20 ? DEF_x__h1835 : DEF__dfoo44;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_11___d21 = DEF_x__h1296 == 11u;
  DEF__dfoo73 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_11___d21 || DEF__dfoo41;
  DEF__dfoo74 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_11___d21 ? DEF_x__h1835 : DEF__dfoo42;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_12___d22 = DEF_x__h1296 == 12u;
  DEF__dfoo71 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_12___d22 || DEF__dfoo39;
  DEF__dfoo72 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_12___d22 ? DEF_x__h1835 : DEF__dfoo40;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_13___d23 = DEF_x__h1296 == 13u;
  DEF__dfoo69 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_13___d23 || DEF__dfoo37;
  DEF__dfoo70 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_13___d23 ? DEF_x__h1835 : DEF__dfoo38;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_14___d24 = DEF_x__h1296 == 14u;
  DEF__dfoo67 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_14___d24 || DEF__dfoo35;
  DEF__dfoo68 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_14___d24 ? DEF_x__h1835 : DEF__dfoo36;
  DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_15___d25 = DEF_x__h1296 == 15u;
  DEF__dfoo65 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_15___d25 || DEF__dfoo33;
  DEF__dfoo66 = DEF_counter_BITS_29_TO_0_CONCAT_0_EQ_15___d25 ? DEF_x__h1835 : DEF__dfoo34;
  DEF_x__h1256 = DEF_x__h1281 + 1u;
  INST_counter.METH_write(DEF_x__h1256);
  if (DEF__dfoo95)
    INST_matrix_vec_0.METH_write(DEF__dfoo96);
  if (DEF__dfoo93)
    INST_matrix_vec_1.METH_write(DEF__dfoo94);
  if (DEF__dfoo91)
    INST_matrix_vec_2.METH_write(DEF__dfoo92);
  if (DEF__dfoo89)
    INST_matrix_vec_3.METH_write(DEF__dfoo90);
  if (DEF__dfoo87)
    INST_matrix_vec_4.METH_write(DEF__dfoo88);
  if (DEF__dfoo85)
    INST_matrix_vec_5.METH_write(DEF__dfoo86);
  if (DEF__dfoo83)
    INST_matrix_vec_6.METH_write(DEF__dfoo84);
  if (DEF__dfoo81)
    INST_matrix_vec_7.METH_write(DEF__dfoo82);
  if (DEF__dfoo77)
    INST_matrix_vec_9.METH_write(DEF__dfoo78);
  if (DEF__dfoo79)
    INST_matrix_vec_8.METH_write(DEF__dfoo80);
  if (DEF__dfoo75)
    INST_matrix_vec_10.METH_write(DEF__dfoo76);
  if (DEF__dfoo73)
    INST_matrix_vec_11.METH_write(DEF__dfoo74);
  if (DEF__dfoo71)
    INST_matrix_vec_12.METH_write(DEF__dfoo72);
  if (DEF__dfoo69)
    INST_matrix_vec_13.METH_write(DEF__dfoo70);
  if (DEF__dfoo67)
    INST_matrix_vec_14.METH_write(DEF__dfoo68);
  if (DEF__dfoo65)
    INST_matrix_vec_15.METH_write(DEF__dfoo66);
  INST_fifo_in.METH_deq();
}


/* Methods */

void MOD_mkBBD::METH_push_data(tUInt32 ARG_push_data_d1)
{
  PORT_EN_push_data = (tUInt8)1u;
  DEF_WILL_FIRE_push_data = (tUInt8)1u;
  PORT_push_data_d1 = ARG_push_data_d1;
  INST_fifo_in.METH_enq(ARG_push_data_d1);
}

tUInt8 MOD_mkBBD::METH_RDY_push_data()
{
  DEF_CAN_FIRE_push_data = INST_fifo_in.METH_i_notFull();
  PORT_RDY_push_data = DEF_CAN_FIRE_push_data;
  return PORT_RDY_push_data;
}


/* Reset routines */

void MOD_mkBBD::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_row_select.reset_RST(ARG_rst_in);
  INST_matrix_vec_9.reset_RST(ARG_rst_in);
  INST_matrix_vec_8.reset_RST(ARG_rst_in);
  INST_matrix_vec_7.reset_RST(ARG_rst_in);
  INST_matrix_vec_6.reset_RST(ARG_rst_in);
  INST_matrix_vec_5.reset_RST(ARG_rst_in);
  INST_matrix_vec_4.reset_RST(ARG_rst_in);
  INST_matrix_vec_3.reset_RST(ARG_rst_in);
  INST_matrix_vec_2.reset_RST(ARG_rst_in);
  INST_matrix_vec_15.reset_RST(ARG_rst_in);
  INST_matrix_vec_14.reset_RST(ARG_rst_in);
  INST_matrix_vec_13.reset_RST(ARG_rst_in);
  INST_matrix_vec_12.reset_RST(ARG_rst_in);
  INST_matrix_vec_11.reset_RST(ARG_rst_in);
  INST_matrix_vec_10.reset_RST(ARG_rst_in);
  INST_matrix_vec_1.reset_RST(ARG_rst_in);
  INST_matrix_vec_0.reset_RST(ARG_rst_in);
  INST_fifo_in.reset_RST(ARG_rst_in);
  INST_dataval.reset_RST(ARG_rst_in);
  INST_counter.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkBBD::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkBBD::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_counter.dump_state(indent + 2u);
  INST_dataval.dump_state(indent + 2u);
  INST_fifo_in.dump_state(indent + 2u);
  INST_matrix_vec_0.dump_state(indent + 2u);
  INST_matrix_vec_1.dump_state(indent + 2u);
  INST_matrix_vec_10.dump_state(indent + 2u);
  INST_matrix_vec_11.dump_state(indent + 2u);
  INST_matrix_vec_12.dump_state(indent + 2u);
  INST_matrix_vec_13.dump_state(indent + 2u);
  INST_matrix_vec_14.dump_state(indent + 2u);
  INST_matrix_vec_15.dump_state(indent + 2u);
  INST_matrix_vec_2.dump_state(indent + 2u);
  INST_matrix_vec_3.dump_state(indent + 2u);
  INST_matrix_vec_4.dump_state(indent + 2u);
  INST_matrix_vec_5.dump_state(indent + 2u);
  INST_matrix_vec_6.dump_state(indent + 2u);
  INST_matrix_vec_7.dump_state(indent + 2u);
  INST_matrix_vec_8.dump_state(indent + 2u);
  INST_matrix_vec_9.dump_state(indent + 2u);
  INST_row_select.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkBBD::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 28u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_RL_matrix_in", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "CAN_FIRE_push_data", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_RL_matrix_in", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "WILL_FIRE_push_data", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "EN_push_data", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "RDY_push_data", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "push_data_d1", 32u);
  num = INST_counter.dump_VCD_defs(num);
  num = INST_dataval.dump_VCD_defs(num);
  num = INST_fifo_in.dump_VCD_defs(num);
  num = INST_matrix_vec_0.dump_VCD_defs(num);
  num = INST_matrix_vec_1.dump_VCD_defs(num);
  num = INST_matrix_vec_10.dump_VCD_defs(num);
  num = INST_matrix_vec_11.dump_VCD_defs(num);
  num = INST_matrix_vec_12.dump_VCD_defs(num);
  num = INST_matrix_vec_13.dump_VCD_defs(num);
  num = INST_matrix_vec_14.dump_VCD_defs(num);
  num = INST_matrix_vec_15.dump_VCD_defs(num);
  num = INST_matrix_vec_2.dump_VCD_defs(num);
  num = INST_matrix_vec_3.dump_VCD_defs(num);
  num = INST_matrix_vec_4.dump_VCD_defs(num);
  num = INST_matrix_vec_5.dump_VCD_defs(num);
  num = INST_matrix_vec_6.dump_VCD_defs(num);
  num = INST_matrix_vec_7.dump_VCD_defs(num);
  num = INST_matrix_vec_8.dump_VCD_defs(num);
  num = INST_matrix_vec_9.dump_VCD_defs(num);
  num = INST_row_select.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkBBD::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBBD &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkBBD::vcd_defs(tVCDDumpType dt, MOD_mkBBD &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 32u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_CAN_FIRE_RL_matrix_in) != DEF_CAN_FIRE_RL_matrix_in)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_RL_matrix_in, 1u);
	backing.DEF_CAN_FIRE_RL_matrix_in = DEF_CAN_FIRE_RL_matrix_in;
      }
      ++num;
      if ((backing.DEF_CAN_FIRE_push_data) != DEF_CAN_FIRE_push_data)
      {
	vcd_write_val(sim_hdl, num, DEF_CAN_FIRE_push_data, 1u);
	backing.DEF_CAN_FIRE_push_data = DEF_CAN_FIRE_push_data;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_RL_matrix_in) != DEF_WILL_FIRE_RL_matrix_in)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_RL_matrix_in, 1u);
	backing.DEF_WILL_FIRE_RL_matrix_in = DEF_WILL_FIRE_RL_matrix_in;
      }
      ++num;
      if ((backing.DEF_WILL_FIRE_push_data) != DEF_WILL_FIRE_push_data)
      {
	vcd_write_val(sim_hdl, num, DEF_WILL_FIRE_push_data, 1u);
	backing.DEF_WILL_FIRE_push_data = DEF_WILL_FIRE_push_data;
      }
      ++num;
      if ((backing.PORT_EN_push_data) != PORT_EN_push_data)
      {
	vcd_write_val(sim_hdl, num, PORT_EN_push_data, 1u);
	backing.PORT_EN_push_data = PORT_EN_push_data;
      }
      ++num;
      if ((backing.PORT_RDY_push_data) != PORT_RDY_push_data)
      {
	vcd_write_val(sim_hdl, num, PORT_RDY_push_data, 1u);
	backing.PORT_RDY_push_data = PORT_RDY_push_data;
      }
      ++num;
      if ((backing.PORT_push_data_d1) != PORT_push_data_d1)
      {
	vcd_write_val(sim_hdl, num, PORT_push_data_d1, 32u);
	backing.PORT_push_data_d1 = PORT_push_data_d1;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_RL_matrix_in, 1u);
      backing.DEF_CAN_FIRE_RL_matrix_in = DEF_CAN_FIRE_RL_matrix_in;
      vcd_write_val(sim_hdl, num++, DEF_CAN_FIRE_push_data, 1u);
      backing.DEF_CAN_FIRE_push_data = DEF_CAN_FIRE_push_data;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_RL_matrix_in, 1u);
      backing.DEF_WILL_FIRE_RL_matrix_in = DEF_WILL_FIRE_RL_matrix_in;
      vcd_write_val(sim_hdl, num++, DEF_WILL_FIRE_push_data, 1u);
      backing.DEF_WILL_FIRE_push_data = DEF_WILL_FIRE_push_data;
      vcd_write_val(sim_hdl, num++, PORT_EN_push_data, 1u);
      backing.PORT_EN_push_data = PORT_EN_push_data;
      vcd_write_val(sim_hdl, num++, PORT_RDY_push_data, 1u);
      backing.PORT_RDY_push_data = PORT_RDY_push_data;
      vcd_write_val(sim_hdl, num++, PORT_push_data_d1, 32u);
      backing.PORT_push_data_d1 = PORT_push_data_d1;
    }
}

void MOD_mkBBD::vcd_prims(tVCDDumpType dt, MOD_mkBBD &backing)
{
  INST_counter.dump_VCD(dt, backing.INST_counter);
  INST_dataval.dump_VCD(dt, backing.INST_dataval);
  INST_fifo_in.dump_VCD(dt, backing.INST_fifo_in);
  INST_matrix_vec_0.dump_VCD(dt, backing.INST_matrix_vec_0);
  INST_matrix_vec_1.dump_VCD(dt, backing.INST_matrix_vec_1);
  INST_matrix_vec_10.dump_VCD(dt, backing.INST_matrix_vec_10);
  INST_matrix_vec_11.dump_VCD(dt, backing.INST_matrix_vec_11);
  INST_matrix_vec_12.dump_VCD(dt, backing.INST_matrix_vec_12);
  INST_matrix_vec_13.dump_VCD(dt, backing.INST_matrix_vec_13);
  INST_matrix_vec_14.dump_VCD(dt, backing.INST_matrix_vec_14);
  INST_matrix_vec_15.dump_VCD(dt, backing.INST_matrix_vec_15);
  INST_matrix_vec_2.dump_VCD(dt, backing.INST_matrix_vec_2);
  INST_matrix_vec_3.dump_VCD(dt, backing.INST_matrix_vec_3);
  INST_matrix_vec_4.dump_VCD(dt, backing.INST_matrix_vec_4);
  INST_matrix_vec_5.dump_VCD(dt, backing.INST_matrix_vec_5);
  INST_matrix_vec_6.dump_VCD(dt, backing.INST_matrix_vec_6);
  INST_matrix_vec_7.dump_VCD(dt, backing.INST_matrix_vec_7);
  INST_matrix_vec_8.dump_VCD(dt, backing.INST_matrix_vec_8);
  INST_matrix_vec_9.dump_VCD(dt, backing.INST_matrix_vec_9);
  INST_row_select.dump_VCD(dt, backing.INST_row_select);
}
