/*
 * Generated by Bluespec Compiler, version 2016.03.beta1 (build 34761, 2016-03-16)
 * 
 * On Thu Sep 29 17:17:49 IST 2016
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkBBDTb.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkBBDTb::MODEL_mkBBDTb()
{
  mkBBDTb_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkBBDTb()
{
  MODEL_mkBBDTb *model = new MODEL_mkBBDTb();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkBBDTb &INST_top = *((MOD_mkBBDTb *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_x_ULT_6___d4;
	 INST_top.INST_dut.PORT_EN_push_data = (tUInt8)0u;
	 INST_top.INST_dut.DEF_WILL_FIRE_push_data = (tUInt8)0u;
	 INST_top.DEF_CAN_FIRE_RL_counter = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_counter = INST_top.DEF_CAN_FIRE_RL_counter;
	 INST_top.DEF_x__h24034 = INST_top.INST_x.METH_read();
	 DEF_INST_top_DEF_x_ULT_6___d4 = (INST_top.DEF_x__h24034) < 6u;
	 INST_top.DEF_CAN_FIRE_RL_rule_data_out = INST_top.INST_dut.METH_RDY_push_data() && DEF_INST_top_DEF_x_ULT_6___d4;
	 INST_top.DEF_WILL_FIRE_RL_rule_data_out = INST_top.DEF_CAN_FIRE_RL_rule_data_out;
	 INST_top.DEF_CAN_FIRE_RL_stop = !DEF_INST_top_DEF_x_ULT_6___d4;
	 INST_top.DEF_WILL_FIRE_RL_stop = INST_top.DEF_CAN_FIRE_RL_stop;
	 INST_top.INST_dut.DEF_CAN_FIRE_RL_matrix_in = INST_top.INST_dut.INST_fifo_in.METH_i_notEmpty() && INST_top.INST_dut.INST_fifo_in.METH_notEmpty();
	 INST_top.INST_dut.DEF_WILL_FIRE_RL_matrix_in = INST_top.INST_dut.DEF_CAN_FIRE_RL_matrix_in;
	 if (INST_top.DEF_WILL_FIRE_RL_stop)
	   INST_top.RL_stop();
	 if (INST_top.INST_dut.DEF_WILL_FIRE_RL_matrix_in)
	   INST_top.INST_dut.RL_matrix_in();
	 if (INST_top.DEF_WILL_FIRE_RL_rule_data_out)
	   INST_top.RL_rule_data_out();
	 if (INST_top.DEF_WILL_FIRE_RL_counter)
	   INST_top.RL_counter();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_dut.INST_fifo_in.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_dut.INST_dataval.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_row_select.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_matrix_vec_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_0.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_3.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_4.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_5.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_6.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_7.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_8.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_9.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_10.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_11.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_12.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_13.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_14.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_15.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_16.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_17.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_18.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_19.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_20.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_21.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_22.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_23.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_24.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_25.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_26.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_27.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_28.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_29.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_30.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_31.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_32.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_33.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_34.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_35.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_36.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_37.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_38.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_39.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_40.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_41.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_42.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_43.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_44.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_45.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_46.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_47.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_48.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_49.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_50.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_51.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_52.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_53.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_54.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_55.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_56.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_57.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_58.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_59.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_60.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_61.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_62.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_63.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_64.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_65.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_66.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_67.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_68.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_69.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_70.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_71.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_72.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_73.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_74.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_75.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_76.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_77.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_78.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_79.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_80.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_81.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_82.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_83.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_84.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_85.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_86.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_87.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_88.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_89.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_90.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_91.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_92.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_93.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_94.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_95.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_96.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_97.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_98.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_99.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_100.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_101.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_102.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_103.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_104.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_105.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_106.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_107.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_108.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_109.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_110.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_111.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_112.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_113.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_114.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_115.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_116.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_117.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_118.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_119.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_120.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_121.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_122.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_123.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_124.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_125.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_126.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_127.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_128.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_129.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_130.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_131.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_132.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_133.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_134.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_135.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_136.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_137.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_138.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_139.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_140.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_141.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_142.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_143.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_144.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_145.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_146.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_147.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_148.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_149.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_150.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_151.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_152.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_153.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_154.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_155.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_156.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_157.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_158.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_159.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_160.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_161.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_162.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_163.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_164.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_165.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_166.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_167.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_168.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_169.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_170.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_171.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_172.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_173.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_174.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_175.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_176.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_177.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_178.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_179.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_180.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_181.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_182.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_183.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_184.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_185.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_186.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_187.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_188.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_189.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_190.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_191.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_192.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_193.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_194.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_195.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_196.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_197.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_198.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_199.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_200.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_201.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_202.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_203.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_204.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_205.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_206.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_207.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_208.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_209.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_210.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_211.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_212.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_213.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_214.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_215.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_216.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_217.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_218.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_219.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_220.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_221.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_222.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_223.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_224.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_225.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_226.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_227.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_228.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_229.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_230.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_231.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_232.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_233.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_234.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_235.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_236.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_237.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_238.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_239.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_240.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_241.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_242.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_243.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_244.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_245.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_246.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_247.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_248.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_249.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_250.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_251.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_252.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_253.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_254.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_255.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_0_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_1_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_2_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_3_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_data_mem_4_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_x.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkBBDTb::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkBBDTb_instance = new MOD_mkBBDTb(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkBBDTb_instance->INST_dut.INST_fifo_in.set_clk_0)("CLK");
  (mkBBDTb_instance->INST_dut.set_clk_0)("CLK");
  (mkBBDTb_instance->set_clk_0)("CLK");
}
void MODEL_mkBBDTb::destroy_model()
{
  delete mkBBDTb_instance;
  mkBBDTb_instance = NULL;
}
void MODEL_mkBBDTb::reset_model(bool asserted)
{
  (mkBBDTb_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkBBDTb::get_instance()
{
  return mkBBDTb_instance;
}

/* Fill in version numbers */
void MODEL_mkBBDTb::get_version(unsigned int *year,
				unsigned int *month,
				char const **annotation,
				char const **build)
{
  *year = 2016u;
  *month = 3u;
  *annotation = "beta1";
  *build = "34761";
}

/* Get the model creation time */
time_t MODEL_mkBBDTb::get_creation_time()
{
  
  /* Thu Sep 29 11:47:49 UTC 2016 */
  return 1475149669llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkBBDTb::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkBBDTb::dump_state()
{
  (mkBBDTb_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkBBDTb & mkBBDTb_backing(tSimStateHdl simHdl)
{
  static MOD_mkBBDTb *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkBBDTb(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkBBDTb::dump_VCD_defs()
{
  (mkBBDTb_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkBBDTb::dump_VCD(tVCDDumpType dt)
{
  (mkBBDTb_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkBBDTb_backing(sim_hdl));
}
